# Usa la imagen de Node.js como base
FROM node:20.9.0 as build

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el package.json y el package-lock.json al directorio de trabajo
COPY server/package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos al directorio de trabajo
COPY ./server .

RUN ls

# Expone el puerto 8080
EXPOSE 8108

# Ejecuta el servidor Express
CMD ["npm", "run", "start"]