name: Onprint demo deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Building & publishing docker container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -t smartposch/demoposfront:1.0.1 -f pos/DockerFile.docker  .
          docker build -t smartposch/demoposbackend:1.0.1 -f server/Dockerfile.docker  .
          docker build -t smartposch/demoshopsmart:1.0.1 -f shop/DockerFile.docker  .
      - uses: docker/login-action@v3
        with:
          username: "smartposch"
          password: "SmartPos2"
      - run: |
          docker push smartposch/demoposfront:1.0.1
          docker push smartposch/demoposbackend:1.0.1
          docker push smartposch/demoshopsmart:1.0.1
      - run: echo "🍏 Build & Publish docker image job status  is ${{ job.status }}."

  deploy:
    needs: build
    name: Deploy Image
    runs-on: ubuntu-22.04
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Create Docker network
        run: docker network create apps-demo
      - name: Deploy React frontend
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH__HOST }}
          username: ${{ secrets.SSH__USER }}
          key: ${{ secrets.SSH__PRIVATE }}
          port: 5069
          script: |
            docker stop onprintFront
            docker container ls -a --format {{.Names}} | grep onprintFront | xargs --no-run-if-empty docker rm -f onprintFront
            echo 'SmartPos2' | docker login -u smartposch --password-stdin
            docker pull smartposch/demoposfront:1.0.1
            docker run --rm -i -t -d -p 5176:5176 \
              --name onprintFront \
              --network apps-demo \
              smartposch/demoposfront:1.0.1
            docker ps
      - name: Deploy Express backend
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH__HOST }}
          username: ${{ secrets.SSH__USER }}
          key: ${{ secrets.SSH__PRIVATE }}
          port: 5069
          script: |
            docker stop onprintBack
            docker container ls -a --format {{.Names}} | grep onprintBack | xargs --no-run-if-empty docker rm -f onprintBack
            echo 'SmartPos2' | docker login -u smartposch --password-stdin
            docker pull smartposch/demoposbackend:1.0.1
            docker run --rm -i -t -d -p 8083:8083 \
              --name onprintBack \
              --network apps-demo \
              smartposch/demoposbackend:1.0.1
            docker ps
      - name: Deploy shop demo
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH__HOST }}
          username: ${{ secrets.SSH__USER }}
          key: ${{ secrets.SSH__PRIVATE }}
          port: 5069
          script: |
            docker stop demoShop
            docker container ls -a --format {{.Names}} | grep demoShop | xargs --no-run-if-empty docker rm -f demoShop
            echo 'SmartPos2' | docker login -u smartposch --password-stdin
            docker pull smartposch/demoshopsmart:1.0.1
            docker run --rm -i -t -d -p  4175:4175 \
              --name demoShop \
              --network apps-demo \
              smartposch/demoshopsmart:1.0.1
            docker ps
